Repository AxonFramework/extension-reactor, pull requests merged in 2020-10, with the labels that each got.

#10 Added dependabot to the project
  .github/dependabot.yml
Labels: Priority 2: Should, Status: Resolved, Type: Dependency Upgrade

#18 [#7] Unwrap errors
  axon-reactor/src/main/java/org/axonframework/extensions/reactor/commandhandling/callbacks/ReactorCallback.java
  axon-reactor/src/main/java/org/axonframework/extensions/reactor/commandhandling/gateway/DefaultReactorCommandGateway.java
  axon-reactor/src/main/java/org/axonframework/extensions/reactor/queryhandling/gateway/DefaultReactorQueryGateway.java
  axon-reactor/src/test/java/org/axonframework/extensions/reactor/commandhandling/callbacks/ReactorCallbackTest.java
  axon-reactor/src/test/java/org/axonframework/extensions/reactor/commandhandling/gateway/DefaultReactorCommandGatewayTest.java
  axon-reactor/src/test/java/org/axonframework/extensions/reactor/queryhandling/gateway/DefaultReactorQueryGatewayTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#12 Add Maven central and SonarCloud badges
  README.md
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement
